# Generated by Django 4.1.2 on 2022-11-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleballpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courts',
            new_name='Court',
        ),
        migrations.AlterModelTable(
            name='court',
            table='Court',
        ),
    ]
