# Generated by Django 4.1.2 on 2022-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleballpages', '0003_alter_court_closingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
