# Generated by Django 4.1.2 on 2022-12-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleballpages', '0004_alter_court_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image',
        ),
    ]
