# Generated by Django 4.1.2 on 2022-12-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleballpages', '0006_alter_court_closingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='courtofficiators',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='court',
            name='lights',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
